### ISSUE TITLE
Installing pyzipcode 3 fails.

### ISSUE THREAD

**Issue by sapkos** [vangheem/pyzipcode#12]
```
> docker run python pip install pyzipcode
```

fails with
```
Collecting pyzipcode
  Downloading pyzipcode-3.0.0.tar.gz (1.9 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a8396ka_/pyzipcode_0dd759e8470e430ab8a3994f1fabab0d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a8396ka_/pyzipcode_0dd759e8470e430ab8a3994f1fabab0d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m9npye19
         cwd: /tmp/pip-install-a8396ka_/pyzipcode_0dd759e8470e430ab8a3994f1fabab0d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a8396ka_/pyzipcode_0dd759e8470e430ab8a3994f1fabab0d/setup.py", line 7, in <module>
        long_description=open("README.md").read() + "\n\n" + open("CHANGES.md").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.md'
```

**Comment by vangheem** [comment]
Can you try 3.0.1?

The manifest was missing some files.

**Comment by sapkos** [comment]
works like a charm, thanks
